name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Docker Login
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

    - name: Build Docker Image
      run: |
        docker build -t angelanez/docker-graphql:0.0.2 .
        docker build -t angelanez/docker-graphql:latest .

    - name: Push Docker Image
      run: |
        docker push angelanez/docker-graphql:0.0.2
        docker push angelanez/docker-graphql:latest

